### ISSUE TITLE
Create Android application for SMS and push notification

### ISSUE THREAD

**Issue by alexvitho** [TechnionYP5777/Smartcity-Smarthouse#129]

**Comment by EliaTraore** [comment]
Changed the label since the "application" label in this context is for any issue relating to apps that work with the system (e.g. vital signs app) or designing API for that kind of apps.
The android app is meant to allow the system to provide its promised services such as phone calls and SMSs, so the "system" label seem more fitting.

**Comment by alexvitho** [comment]
Steps:

- [ ] Install Android studio and open Heroku server
- [ ] Complete basic tutorials
- [ ] Create application 
- [ ] Connect the application to the project
