### ISSUE TITLE
Bidirectional connection with sensors

### ISSUE THREAD

**Issue by ylevv** [TechnionYP5777/Smartcity-Smarthouse#137]
In order to achieve the goals mentioned in #130 , some sensors-related changes must be made. As I see it right now, the required changes are:
- [ ] Suport a second TCP connection for each `InteractiveSensor` ("client")
- [x] Write another "server" in the system
- [x] Think of a way to inform the server when a message needs to be sent

These tasks might change after a discussion with @EliaTraore from the applications' point of view.

Working-time estimation: 2 days

**Comment by EliaTraore** [comment]
changed the label since the progress on #130 depends on the products of this issue

**Comment by ylevv** [comment]
@EliaTraore The method you requested is now available: `sendInstructions(UpdateMessage instruction)`.
I assumed the applications send a message of type `UpdateMessage` as it is very flexible; if you wish it may be changed.
@RonGatenio Opinions?
In addition, do you think it is reasonable to make each sensor handle incoming instructions on its own? Or should we provide some sort of general "server side"?

**Comment by EliaTraore** [comment]
`UpdateMessage` is fine - one of the various wrappers will transform a `Map<String,String>` to `UpdateMessage`, the apps won't even know
As for the server-side in the sensor  - I'm not quite sure this is what you meant, but as I see it, the `InteractiveSensor` should have a method that takes the message from the inputstream and extracts the instruction it in. Since it is still a sensor, this producer method cannot be blocking (so the bufferedreader should be first checked with `ready()` before any read attempt). And because it's not blocking there will be need for polling. 
for the polling there are 2 options - 
- the consumer method will be called by the user (i.e. whoever writes the sensor gui)
- the consumer method will be called automatically every x [time unit] and the product will be put in a queue / consumed by a given function

IDK if option 2 isn't overkill, but if its not - I've worked with timed taskes in the `ApplicationHandler` and I think looking into the `QueryTimerTask` class there would help you with the implementation :)
