### ISSUE TITLE
Sensors are not shown in the sensors tab

### ISSUE THREAD

**Issue by rodedzats** [TechnionYP5777/Smartcity-Smarthouse#233]
I can not see the available sensors in the Sensors tab as described here:
https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/User-Manual#house-mapping
Attaching a screenshot
![5](https://user-images.githubusercontent.com/15691986/27768933-f0cf5c8c-5f27-11e7-8465-efe0d581198e.png)

**Comment by EliaTraore** [comment]
The house is a stand alone application - in a "real scenrio" you would install apps and sensors on it, just like you would on your phone (except the sensor part).
However, we have a demo module showing how a house would look with applications and sensors connected, but due to a technical error we didn't upload that module as part of the release - we're currently working on a revision to our release ( @RonGatenio  will keep you posted)
In the mean time, you can download from the release the .zip, and run an application in developer mode, it will open with the application and sensor already installed and give you at least a partial experience.

**Comment by EliaTraore** [comment]
Update: (wonders of the cs_conference)
the release have been updated, please download `ApplicationsIncludedHouse-1.01-jar-with-dependencies.jar`.

**Comment by rodedzats** [comment]
Thanks! I'll try it now

**Comment by roy-shchory** [comment]
@DavidCohen55 we addressed your question here

**Comment by DavidCohen55** [comment]
Where can I find the download @EliaTraore

**Comment by EliaTraore** [comment]
The first jar in our [last release](https://github.com/TechnionYP5777/Smartcity-Smarthouse/releases) :)
