### ISSUE TITLE
adding sensors to rooms 

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Smartcity-Smarthouse#255]
When I add more than one room with the same name and select just one of them to add a sensor to it is added to both:
![image](https://user-images.githubusercontent.com/22842727/27789287-ab6fc1f4-5ff4-11e7-90d6-ad88cac87f81.png)

also the "undefined" room stays in the list and i is possible to add sensors to it:
![image](https://user-images.githubusercontent.com/22842727/27789384-133e5b1a-5ff5-11e7-8592-42e7a7c914d8.png)

**Comment by EliaTraore** [comment]
About the duplicate name room - you're right, we should've prevented adding a room with an existing name. Currently being fixed.
Regarding the "undefined" room, shortly - by design you should be able to add sensors to the room, to allow mapping unique sensors (like a vitals sensors which on the preson and not located in a place). read more about it here: #242
